CREATE TABLE topicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL UNIQUE,
    mensaje VARCHAR(500) NOT NULL UNIQUE,
    fecha_creacion DATETIME NOT NULL,
    status VARCHAR(50) NOT NULL,
    autor_id VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    activo TINYINT NOT NULL,

    PRIMARY KEY (id)
);